### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by ghost** [dzmanto/gzplugin4micro#1]
When trying to install the error, in repo.json the json file is not well formatted, you need to remove a comma

**Comment by dzmanto** [comment]
Hi Taconi,

can you send me the output of
# diff your_repo.json my_repo..json
please?

Cheers,

Daniela
________________________________
From: taconi ***@***.***>
Sent: Sunday, 12 November 2023 4:06 PM
To: dzmanto/gzplugin4micro ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [dzmanto/gzplugin4micro] Installation error (Issue #1)


When trying to install the error, in repo.json the json file is not well formatted, you need to remove a comma

**Comment by ghost** [comment]
I found it easier to create a PR

**Comment by dzmanto** [comment]
Thank you for the heads-up. I fixed the comma in repo.json of gzplugin.

Cheers,

Daniela


________________________________________

**Comment by ghost** [comment]
Using website [jsonlint](https://jsonlint.com/) you can see that the repo.json file has a formatting error, as the image below can show ![image](https://github.com/dzmanto/gzplugin4micro/assets/44283700/ccf0e65f-9ed8-465c-a985-4343d16fbc42).

I updated PR #2 with commit [f013d95](https://github.com/dzmanto/gzplugin4micro/commit/f013d95c4110ce5d80c43345e2092bde55aeb6fc), in this pull request the repo.json is adjusted.

**Comment by dzmanto** [comment]
I just fixed the json. Thanks for the heads-up.
